# Generated by Django 5.2.1 on 2025-05-22 03:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_pjsell", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="contato",
            name="dia",
            field=models.DateTimeField(
                auto_now_add=True,
                default=datetime.datetime(2025, 5, 22, 0, 4, 11, 908495),
            ),
            preserve_default=False,
        ),
    ]
