# Generated by Django 5.2.1 on 2025-05-28 02:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app_pjsell", "0004_alter_contato_data_m1"),
    ]

    operations = [
        migrations.CreateModel(
            name="Configuracao",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("mensagem_1", models.TextField(blank=True)),
                ("mensagem_2", models.TextField(blank=True)),
                ("data_mensagem_2", models.DateField(blank=True, null=True)),
                ("hora_mensagem_2", models.TimeField(blank=True, null=True)),
                ("mensagem_3", models.TextField(blank=True)),
                ("data_mensagem_3", models.DateField(blank=True, null=True)),
                ("hora_mensagem_3", models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
